version: '3.8'

services:
  # Run the PostgreSQL database
  db:
    image: postgres:14
    container_name: book_crud_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: book_crud_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Run the application
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: book_crud_db
      PORT: 8080
    volumes:
      - .env:/app/.env
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data: